# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_confirmation', '0002_auto_20150222_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
