# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_confirmation', '0004_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='confirmation_key',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddIndex(
            model_name='emailconfirmation',
            index=models.Index(fields=['person'], name='email_confi_person__94b5d3_idx'),
        ),
        migrations.AddIndex(
            model_name='emailconfirmation',
            index=models.Index(fields=['confirmation_key'], name='email_confi_confirm_003013_idx'),
        ),
    ]
