# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import gallery.models.image


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20150509_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='large_thumbnail_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='large_thumbnail_width',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='original_image_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='original_image_width',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_width',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='large_thumbnail',
            field=models.ImageField(blank=True, height_field='large_thumbnail_height', upload_to=gallery.models.image.upload_to, width_field='large_thumbnail_width'),
        ),
        migrations.AlterField(
            model_name='image',
            name='original_image',
            field=models.ImageField(blank=True, height_field='original_image_height', upload_to=gallery.models.image.upload_to, width_field='original_image_width'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, height_field='thumbnail_height', upload_to=gallery.models.image.upload_to, width_field='thumbnail_width'),
        ),
    ]
