# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 14:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20160317_1916'),
    ]

    operations = [
        migrations.RunSQL("UPDATE gallery_image SET date_taken=creation_date WHERE date_taken IS NULL;"),
        migrations.AlterField(
            model_name='image',
            name='date_taken',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2016, 4, 27, 14, 26, 6, 347165, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
