# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20160427_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='date_taken',
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['title'], name='gallery_gal_title_8b9e75_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['family'], name='gallery_gal_family__f3763b_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['creation_date'], name='gallery_gal_creatio_f11c00_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['gallery'], name='gallery_ima_gallery_fe31d7_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['family'], name='gallery_ima_family__6fde05_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['date_taken'], name='gallery_ima_date_ta_aa4978_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['image'], name='gallery_tag_image_i_1c6e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['person'], name='gallery_tag_person__ed1c35_idx'),
        ),
    ]
