# Generated by Django 2.2.4 on 2019-08-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20170417_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='thumbnail_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='thumbnail_width',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='thumbnail',
            field=models.ImageField(blank=True, height_field='thumbnail_height', upload_to='', width_field='thumbnail_width'),
        ),
    ]
