# Generated by Django 2.2.6 on 2019-10-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20190920_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='face_detected',
            field=models.BooleanField(default=False),
        ),
    ]
