# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import family_tree.models.person


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0009_auto_20150415_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh-tw', 'Traditional Chinese'), ('zh-cn', 'Simplified Chinese'), ('pl', 'Polish'), ('fi', 'Finnish'), ('fr', 'French')], db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=family_tree.models.person.NullableEmailField(blank=True, default=None, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh-tw', 'Traditional Chinese'), ('zh-cn', 'Simplified Chinese'), ('pl', 'Polish'), ('fi', 'Finnish'), ('fr', 'French')], default='en', max_length=5),
        ),
    ]
