# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0011_merge'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='biography',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='biography',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='biography',
            field=models.TextField(blank=True, null=False),
        ),
        migrations.DeleteModel(
            name='Biography',
        ),
    ]
