# Generated by Django 2.2.6 on 2019-10-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0013_auto_20170417_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Non-Binary'), ('O', 'Other'), ('P', 'Prefer Not To Say')], max_length=1),
        ),
    ]
