# Generated by Django 2.2.6 on 2019-10-12 10:35

from django.db import migrations, models

def create_profile_photo_queue(apps, schema_editor):
    Queue = apps.get_model("message_queue", "Queue")
    queue = Queue(name = "profile_photo_process",
                    description = """
                    Queue for person ids that have had profile photos updated.
                    These need to be analysed to help with Face Recognition
                    """)
    queue.save()

def create_tag_converted_queue(apps, schema_editor):
    Queue = apps.get_model("message_queue", "Queue")
    queue = Queue(name = "tag_converted_process",
                    description = """
                    Queue for tag ids that have been converted from a sugested tag
                    These need to be analysed to help with Face Recognition
                    """)
    queue.save()

class Migration(migrations.Migration):

    dependencies = [
        ('message_queue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='error_message',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['error'], name='message_que_error_8debc9_idx'),
        ),
        migrations.RunPython(create_profile_photo_queue),
        migrations.RunPython(create_tag_converted_queue),
    ]
