# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0004_auto_20160424_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='confirmation_key',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddIndex(
            model_name='signup',
            index=models.Index(fields=['confirmation_key'], name='sign_up_sig_confirm_0cebcd_idx'),
        ),
    ]
