# Generated by Django 2.2.5 on 2019-09-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0005_auto_20170417_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
