# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailer', '0007_auto_20150509_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='recipient',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
