# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailer', '0008_auto_20151224_1528'),
        ('emailer', '0008_auto_20151226_2245'),
    ]

    operations = [
    ]
