# Generated by Django 2.2.6 on 2019-10-04 20:21

from django.db import migrations, models
import django.db.models.deletion

def create_image_face_detect(apps, schema_editor):
    Queue = apps.get_model("message_queue", "Queue")
    image_face_detect_queue = Queue(name = "image_face_detect",
                    description = """
                    Queue to record image ids that need to be to have using AI facial recognition
                    run on them.  integer_data set to image.id
                    """)
    image_face_detect_queue.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family_tree', '0014_auto_20191004_1022'),
        ('gallery', '0008_auto_20190920_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField(null=True)),
                ('x1', models.FloatField()),
                ('y1', models.FloatField()),
                ('x2', models.FloatField()),
                ('y2', models.FloatField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Image')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='family_tree.Person')),
            ],
        ),
        migrations.AddIndex(
            model_name='suggestedtag',
            index=models.Index(fields=['image'], name='suggested_i_image_i_cf4e07_idx'),
        ),
        migrations.RunPython(create_image_face_detect),
    ]
